especialidad:
    path:     /
    defaults: { _controller: "AcmeHelloBundle:Especialidad:index" }

especialidad_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeHelloBundle:Especialidad:show" }

especialidad_new:
    path:     /new
    defaults: { _controller: "AcmeHelloBundle:Especialidad:new" }

especialidad_create:
    path:     /create
    defaults: { _controller: "AcmeHelloBundle:Especialidad:create" }
    requirements: { _method: post }

especialidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeHelloBundle:Especialidad:edit" }

especialidad_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeHelloBundle:Especialidad:update" }
    requirements: { _method: post|put }

especialidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeHelloBundle:Especialidad:delete" }
    requirements: { _method: post|delete }
